[package]
name = "async_ratatui"
version = "0.1.0"
edition = "2021"


[lib]
name = "async_ratatui_core"
path = "src/lib.rs"

[[bin]]
name = "async_ratatui"
path = "src/main.rs"

[dependencies]
rand = "0.9.0"
ratatui = "0.29.0"
tokio = { version = "1.40.0", features = ["full"] }
